
import { useState } from "react";
import { useToast } from "@/hooks/use-toast";
import { JournalEntry } from "@/types/wellness";
import jsPDF from 'jspdf';

export const useJournalEntries = () => {
  const [currentEntry, setCurrentEntry] = useState<JournalEntry>({
    date: new Date().toISOString().split('T')[0],
    mood: 5,
    energy: 5,
    stress: 5,
    sleep: 5,
    recovery: 5,
    notes: '',
    goals: '',
    gratitude: ''
  });
  
  const [savedEntries, setSavedEntries] = useState<JournalEntry[]>([]);
  const { toast } = useToast();

  const handleScaleChange = (field: keyof JournalEntry, value: number) => {
    setCurrentEntry(prev => ({ ...prev, [field]: value }));
  };

  const handleTextChange = (field: keyof JournalEntry, value: string) => {
    setCurrentEntry(prev => ({ ...prev, [field]: value }));
  };

  const generatePDF = (entry: JournalEntry) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;
    const margin = 20;
    let yPosition = 30;

    // Title
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('Wellness Journal Entry', pageWidth / 2, yPosition, { align: 'center' });
    
    yPosition += 20;
    
    // Date
    doc.setFontSize(16);
    doc.setFont('helvetica', 'normal');
    doc.text(`Date: ${new Date(entry.date).toLocaleDateString()}`, margin, yPosition);
    
    yPosition += 20;

    // Wellness Metrics
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Wellness Metrics (1-10 scale):', margin, yPosition);
    yPosition += 15;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(12);
    
    const metrics = [
      { label: 'Mood', value: entry.mood },
      { label: 'Energy Level', value: entry.energy },
      { label: 'Stress Level', value: entry.stress },
      { label: 'Sleep Quality', value: entry.sleep },
      { label: 'Recovery', value: entry.recovery }
    ];

    metrics.forEach(metric => {
      doc.text(`${metric.label}: ${metric.value}/10`, margin, yPosition);
      yPosition += 10;
    });

    yPosition += 10;

    // Text sections
    const textSections = [
      { title: 'Daily Notes & Reflections', content: entry.notes },
      { title: 'Goals & Intentions', content: entry.goals },
      { title: 'Gratitude & Wins', content: entry.gratitude }
    ];

    textSections.forEach(section => {
      if (section.content.trim()) {
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(14);
        doc.text(section.title + ':', margin, yPosition);
        yPosition += 10;

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(11);
        
        // Split text into lines that fit the page width
        const lines = doc.splitTextToSize(section.content, pageWidth - 2 * margin);
        lines.forEach((line: string) => {
          if (yPosition > 270) {
            doc.addPage();
            yPosition = 20;
          }
          doc.text(line, margin, yPosition);
          yPosition += 7;
        });
        
        yPosition += 10;
      }
    });

    // Footer
    yPosition = doc.internal.pageSize.height - 20;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'italic');
    doc.text('Generated by Wellness Tracker', pageWidth / 2, yPosition, { align: 'center' });

    return doc;
  };

  const saveEntry = () => {
    const newEntries = [...savedEntries, currentEntry];
    setSavedEntries(newEntries);
    localStorage.setItem('wellness-entries', JSON.stringify(newEntries));
    
    // Generate and download PDF
    const pdf = generatePDF(currentEntry);
    const fileName = `wellness-entry-${currentEntry.date}.pdf`;
    pdf.save(fileName);
    
    toast({
      title: "Entry saved! 🌟",
      description: "Your wellness data has been recorded and PDF downloaded.",
    });

    // Reset for next entry
    setCurrentEntry({
      date: new Date().toISOString().split('T')[0],
      mood: 5,
      energy: 5,
      stress: 5,
      sleep: 5,
      recovery: 5,
      notes: '',
      goals: '',
      gratitude: ''
    });
  };

  return {
    currentEntry,
    savedEntries,
    handleScaleChange,
    handleTextChange,
    saveEntry
  };
};
